/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#0b1f13",
        "background": "#fbf9f4",
        "secondary-fixed-dim": "#c2c9bc",
        "accent-indigo": "#4a6741",
        "on-error-container": "#410002",
        "primary-fixed": "#c0ecb2",
        "tertiary-fixed": "#c3ecd5",
        "tertiary-fixed-dim": "#a7d0b9",
        "secondary": "#55624c",
        "primary-container": "#cceebf",
        "inverse-on-surface": "#f2f0eb",
        "surface-bright": "#fbf9f4",
        "on-secondary-fixed": "#161e13",
        "inverse-surface": "#30302e",
        "on-primary-fixed-variant": "#2a4e23",
        "surface-container-high": "#e9e6df",
        "surface-dim": "#dbdad5",
        "on-surface-variant": "#43483e",
        "error-container": "#ffdad6",
        "text-secondary": "#43483e",
        "text-primary": "#1a1c18",
        "on-secondary-container": "#131f0d",
        "on-secondary-fixed-variant": "#41493e",
        "tertiary-container": "#bbecec",
        "surface-container-highest": "#e4e1d9",
        "secondary-container": "#d8e7cb",
        "error": "#ba1a1a",
        "surface": "#fbf9f4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#012201",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dde5d6",
        "outline": "#73796d",
        "on-primary-container": "#0c2006",
        "tertiary": "#386667",
        "surface-tint": "#426738",
        "on-error": "#ffffff",
        "inverse-primary": "#a5d098",
        "surface-variant": "#dfe4d7",
        "outline-variant": "#c3c8bc",
        "on-tertiary-fixed-variant": "#294e3b",
        "primary": "#4a6741",
        "on-background": "#191c19",
        "on-surface": "#1a1c18",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#efece5",
        "primary-fixed-dim": "#a5d098",
        "on-tertiary-container": "#002020"
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem"
      },
      borderRadius: {
        "24px": "24px",
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "xl": "40px",
        "2xl": "64px",
        "sm": "8px",
        "xs": "4px",
        "gutter": "20px",
        "lg": "24px",
        "margin": "32px"
      },
      fontFamily: {
        "headline-lg": ["Literata"],
        "headline-md": ["Literata"],
        "headline-sm": ["Literata"],
        "label-md": ["Literata"],
        "body-lg": ["Literata"],
        "headline-lg-mobile": ["Literata"],
        "display-lg": ["Literata"],
        "body-md": ["Literata"],
        "code-md": ["JetBrains Mono"],
        "body-sm": ["Literata"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
